-- create required databases

CREATE DATABASE IF NOT EXISTS userdb;
CREATE DATABASE IF NOT EXISTS productdb;
CREATE DATABASE IF NOT EXISTS orderdb;
CREATE DATABASE IF NOT EXISTS paymentdb;

-- populate databases with some demo values
use productdb;
-- Insert categories
INSERT INTO category (name) VALUES
('Electronics'),
('Clothing'),
('Home & Kitchen'),
('Books'),
('Sports & Outdoors'),
('Beauty & Personal Care'),
('Toys & Games'),
('Automotive'),
('Grocery'),
('Health & Household');

-- Insert 100 products with random data
INSERT INTO product (description, name, price, stock, category_id) VALUES
('High-performance smartphone with advanced camera', 'Smartphone X', 899.99, 50, 1),
('Wireless noise-canceling headphones', 'Premium Headphones', 349.99, 30, 1),
('Cotton t-shirt with comfortable fit', 'Classic T-Shirt', 19.99, 200, 2),
('Non-stick frying pan for professional cooking', 'Chef''s Frying Pan', 49.99, 80, 3),
('Bestselling fiction novel', 'Mystery Novel', 14.99, 150, 4),
('Professional football for matches', 'Match Football', 29.99, 60, 5),
('Moisturizing cream for dry skin', 'Hydrating Cream', 24.99, 120, 6),
('Building blocks set for creative play', 'Construction Set', 39.99, 90, 7),
('Synthetic motor oil for cars', 'Engine Oil 5W-30', 34.99, 70, 8),
('Organic whole grain pasta', 'Whole Wheat Pasta', 3.99, 300, 9),
('Digital thermometer for accurate readings', 'Medical Thermometer', 12.99, 110, 10),
('Ultra HD Smart TV with HDR', '55-inch Smart TV', 799.99, 25, 1),
('Fitness tracker with heart rate monitor', 'Activity Tracker', 89.99, 65, 1),
('Denim jeans with modern fit', 'Slim Fit Jeans', 59.99, 85, 2),
('Stainless steel kitchen knife set', 'Chef''s Knife Set', 79.99, 40, 3),
('Self-help book for personal growth', 'Motivational Book', 12.99, 95, 4),
('Yoga mat for comfortable practice', 'Non-Slip Yoga Mat', 29.99, 75, 5),
('Anti-aging serum with retinol', 'Revitalizing Serum', 49.99, 55, 6),
('Board game for family entertainment', 'Family Board Game', 34.99, 45, 7),
('Car air freshener with long-lasting scent', 'Vanilla Air Freshener', 5.99, 200, 8),
('Organic fair trade coffee beans', 'Premium Coffee', 9.99, 130, 9),
('Multivitamin supplements for adults', 'Daily Multivitamin', 19.99, 180, 10),
('Bluetooth speaker with deep bass', 'Portable Speaker', 129.99, 35, 1),
('Gaming laptop with high-end graphics', 'Gaming Laptop', 1499.99, 15, 1),
('Winter jacket with thermal insulation', 'Winter Parka', 199.99, 30, 2),
('Electric blender for smoothies', 'High-Speed Blender', 89.99, 50, 3),
('Cookbook with healthy recipes', 'Healthy Eating Guide', 24.99, 70, 4),
('Dumbbell set for home workouts', 'Adjustable Dumbbells', 79.99, 25, 5),
('Facial cleanser for sensitive skin', 'Gentle Cleanser', 17.99, 90, 6),
('Puzzle game for brain training', 'Brain Teaser Puzzle', 14.99, 60, 7),
('Car phone mount for safe driving', 'Dashboard Phone Holder', 19.99, 100, 8),
('Organic coconut oil for cooking', 'Virgin Coconut Oil', 7.99, 150, 9),
('Nasal decongestant for cold relief', 'Breathing Aid Spray', 8.99, 120, 10),
('Wireless charging pad for smartphones', 'Qi Charging Pad', 29.99, 80, 1),
('Smartwatch with fitness tracking', 'Smart Watch Pro', 199.99, 40, 1),
('Formal dress shirt for business', 'Business Shirt', 49.99, 65, 2),
('Air fryer for healthy cooking', 'Digital Air Fryer', 119.99, 30, 3),
('Science fiction bestseller', 'Sci-Fi Novel', 15.99, 85, 4),
('Running shoes with cushioning', 'Performance Running Shoes', 89.99, 45, 5),
('Shampoo for color-treated hair', 'Color Protection Shampoo', 12.99, 110, 6),
('Educational toy for toddlers', 'Learning Toy Set', 29.99, 70, 7),
('Car vacuum cleaner for interiors', 'Portable Car Vacuum', 39.99, 50, 8),
('Organic green tea bags', 'Antioxidant Green Tea', 5.99, 200, 9),
('Pain relief cream for muscles', 'Muscle Relief Gel', 11.99, 90, 10),
('External SSD for fast storage', '1TB Portable SSD', 149.99, 25, 1),
('Noise-canceling wireless earbuds', 'True Wireless Earbuds', 179.99, 35, 1),
('Wool sweater for cold weather', 'Knit Sweater', 69.99, 40, 2),
('Slow cooker for easy meals', 'Programmable Slow Cooker', 59.99, 55, 3),
('Biography of famous scientist', 'Scientific Biography', 18.99, 60, 4),
('Camping tent for 4 people', 'Family Camping Tent', 149.99, 20, 5),
('Sunscreen with high SPF protection', 'SPF 50 Sunscreen', 14.99, 95, 6),
('Remote control car for kids', 'RC Racing Car', 49.99, 45, 7),
('Car jump starter for emergencies', 'Portable Jump Starter', 99.99, 30, 8),
('Organic honey from local farms', 'Raw Honey', 8.99, 130, 9),
('Thermal socks for cold feet', 'Wool Thermal Socks', 12.99, 85, 2),
('Electric toothbrush with timer', 'Sonic Toothbrush', 59.99, 60, 10),
('4K action camera for adventures', 'Waterproof Action Cam', 299.99, 15, 1),
('Leather wallet with RFID protection', 'Men''s Leather Wallet', 39.99, 70, 2),
('Espresso machine for home use', 'Home Espresso Maker', 199.99, 25, 3),
('Historical fiction novel', 'Period Drama Book', 16.99, 80, 4),
('Yoga blocks for support', 'Foam Yoga Blocks', 19.99, 65, 5),
('Makeup palette with neutral tones', 'Eyeshadow Palette', 34.99, 50, 6),
('Building toy for creative minds', 'STEM Building Kit', 49.99, 40, 7),
('Car seat covers for protection', 'Neoprene Seat Covers', 69.99, 35, 8),
('Organic almond butter', 'Creamy Almond Butter', 6.99, 110, 9),
('Blood pressure monitor', 'Digital BP Monitor', 39.99, 45, 10),
('Graphic tablet for digital art', 'Drawing Tablet', 249.99, 20, 1),
('Wireless mechanical keyboard', 'Gaming Keyboard', 129.99, 30, 1),
('Silk scarf for elegant look', 'Ladies Silk Scarf', 29.99, 55, 2),
('Food processor for kitchen', 'Multi-function Processor', 89.99, 40, 3),
('Cookbook for beginners', 'Basic Cooking Guide', 19.99, 75, 4),
('Hiking backpack with hydration', 'Outdoor Backpack', 79.99, 35, 5),
('Anti-dandruff shampoo', 'Medicated Shampoo', 9.99, 100, 6),
('Jigsaw puzzle for adults', '1000-Piece Puzzle', 24.99, 60, 7),
('Car polish for shine', 'Premium Car Wax', 14.99, 80, 8),
('Organic quinoa for cooking', 'Whole Grain Quinoa', 4.99, 150, 9),
('First aid kit for emergencies', 'Comprehensive First Aid Kit', 29.99, 50, 10),
('Portable projector for movies', 'Mini HD Projector', 179.99, 25, 1),
('Fitness smart scale', 'Body Composition Scale', 49.99, 40, 1),
('Cashmere sweater luxury', 'Premium Cashmere', 149.99, 20, 2),
('Indoor grill for healthy cooking', 'Electric Grill', 79.99, 30, 3),
('Language learning book', 'Spanish for Beginners', 22.99, 65, 4),
('Resistance bands set', 'Workout Bands Set', 19.99, 85, 5),
('Perfume with floral notes', 'Eau de Parfum', 59.99, 45, 6),
('Drone with HD camera', 'Quadcopter Drone', 199.99, 15, 7),
('Car phone charger fast', 'Quick Charge Adapter', 24.99, 90, 8),
('Organic dark chocolate', '70% Cocoa Chocolate', 3.99, 120, 9),
('Knee support brace', 'Compression Knee Brace', 17.99, 70, 10),
('E-reader with backlight', 'Digital E-Reader', 129.99, 35, 1),
('Wireless gaming mouse', 'Ergonomic Gaming Mouse', 79.99, 45, 1),
('Leather belt for men', 'Genuine Leather Belt', 34.99, 60, 2),
('Stand mixer for baking', 'Professional Mixer', 249.99, 15, 3),
('Personal finance book', 'Money Management Guide', 18.99, 55, 4),
('Cycling helmet for safety', 'Bike Helmet', 49.99, 40, 5),
('Hair dryer with diffuser', 'Ionic Hair Dryer', 39.99, 50, 6),
('Model building kit', 'Aircraft Model Kit', 29.99, 65, 7),
('Car floor mats custom', 'All-Weather Mats', 59.99, 35, 8),
('Organic maple syrup', 'Pure Maple Syrup', 8.99, 95, 9),
('Neck massager for relaxation', 'Shiatsu Massager', 49.99, 30, 10),
('Smart home assistant', 'Voice Assistant', 99.99, 40, 1),
('Wireless presenter remote', 'Presentation Clicker', 29.99, 70, 1),
('Winter gloves touchscreen', 'Thermal Gloves', 24.99, 50, 2),
('Rice cooker with timer', 'Automatic Rice Cooker', 59.99, 45, 3),
('Photography technique book', 'Digital Photography Guide', 27.99, 60, 4),
('Jump rope for fitness', 'Speed Jump Rope', 14.99, 80, 5),
('Men''s grooming kit', 'Beard Care Set', 34.99, 55, 6),
('Magic trick set', 'Beginner Magic Kit', 19.99, 65, 7),
('Car emergency kit', 'Roadside Assistance Kit', 39.99, 40, 8),
('Organic herbal tea', 'Relaxing Tea Blend', 5.99, 110, 9),
('Compression socks', 'Medical Grade Socks', 16.99, 75, 10);